logging:
  level:
    root: INFO
    org.springframework: INFO
    pe.financieraoh.apiseguro: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.simple.SimpleJdbcCall: INFO
    org.springframework.web.client.RestTemplate: INFO


server:
  servlet:
    context-path: /api-seguro

spring:
  application:
    name: apiseguro
  main:
    banner-mode: "off"
  jmx:
    enabled: false
  jpa:
    show-sql: false
    database: oracle
    hibernate:
      ddl-auto: none             
  datasource:
    platform: oracle
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.20.17.11:1540:FULXT01C
    username: EFINAN
    password: FUNO2016
    
info:
  app:
    name: Api Seguro
    description: Api para cancelar seguros
    version: 1.0.0
    
#management:
#  endpoints:
#    web:
#      exposure:
#        include: env,beans